### ISSUE TITLE
The environment file is broken?

### ISSUE THREAD

**Issue by linzhiqiu** [Hxyou/IdealGPT#1]
It seems the environment file contains conflict such that I cannot use it. For example:
`Package python conflicts for:
pygments==2.14.0=pyhd8ed1ab_0 -> python[version='>=3.6']
pip==23.0.1=py38h06a4308_0 -> python[version='>=3.8,<3.9.0a0']
setuptools==65.6.3=py38h06a4308_0 -> python[version='>=3.8,<3.9.0a0']
decorator==5.1.1=pyhd8ed1ab_0 -> python[version='>=3.5']
python-dateutil==2.8.2=pyhd8ed1ab_0 -> python[version='>=3.6']
certifi==2022.12.7=pyhd8ed1ab_0 -> python[version='>=3.7']
asttokens==2.2.1=pyhd8ed1ab_0 -> python[version='>=3.5']
entrypoints==0.4=pyhd8ed1ab_0 -> python[version='>=3.6']
jupyter_client==7.0.6=pyhd8ed1ab_0 -> python[version='>=3.6.1']
backports.functools_lru_cache==1.6.4=pyhd8ed1ab_0 -> python[version='>=3.6']
wcwidth==0.2.6=pyhd8ed1ab_0 -> python[version='>=3.6']
packaging==23.0=pyhd8ed1ab_0 -> python[version='>=3.7']
parso==0.8.3=pyhd8ed1ab_0 -> python[version='>=3.6']
pickleshare==0.7.5=py_1003 -> python[version='>=3']
pure_eval==0.2.2=pyhd8ed1ab_0 -> python[version='>=3.5']
six==1.16.0=pyh6c4a22f_0 -> python
ipython==8.11.0=pyh41d4057_0 -> python[version='>=3.8']
pexpect==4.8.0=pyh1a96a4e_2 -> python
psutil==5.9.0=py38h5eee18b_0 -> python[version='>=3.8,<3.9.0a0']
pyzmq==19.0.2=py38ha71036d_2 -> python[version='>=3.8,<3.9.0a0']
debugpy==1.5.1=py38h295c915_0 -> python[version='>=3.8,<3.9.0a0']
executing==1.2.0=pyhd8ed1ab_0 -> python[version='>=2.7']`

**Comment by Hxyou** [comment]
@ThreeSR  Hi Rui, can you help to check whether the conflict happens in your case?

**Comment by ThreeSR** [comment]
@Hxyou Hi Haoxuan, it works well in my case. Could you please help me double-check if the conflict happens in your case? Thanks.

**Comment by Hxyou** [comment]
I also found an error when creating the environment through conda. Rui, can you help to deal with that? Thanks

```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - jedi==0.18.2=pyhd8ed1ab_0
  - ipython==8.11.0=pyh41d4057_0
  - platformdirs==3.1.1=pyhd8ed1ab_0
  - packaging==23.0=pyhd8ed1ab_0
  - ca-certificates==2022.12.7=ha878542_0
  - certifi==2022.12.7=pyhd8ed1ab_0
  - prompt_toolkit==3.0.38=hd8ed1ab_0
  - wcwidth==0.2.6=pyhd8ed1ab_0
  - asttokens==2.2.1=pyhd8ed1ab_0
  - backports==1.0=pyhd8ed1ab_3
  - prompt-toolkit==3.0.38=pyha770c72_0
  - traitlets==5.9.0=pyhd8ed1ab_0
  - typing-extensions==4.5.0=hd8ed1ab_0
  - pygments==2.14.0=pyhd8ed1ab_0
  - typing_extensions==4.5.0=pyha770c72_0
  - jupyter_core==5.2.0=py38h578d9bd_0
  - stack_data==0.6.2=pyhd8ed1ab_0
  ```

**Comment by ThreeSR** [comment]
@linzhiqiu @Hxyou Sorry for the late reply. I think the error has been fixed. You can use the updated [environment.yml](https://github.com/Hxyou/IdealGPT/blob/master/environment.yml). If you have any questions, please let us know. Thanks.

**Comment by Hxyou** [comment]
Close the issue for now. Let me know if this error still exists.
