### ISSUE TITLE
How to run the baseline.

### ISSUE THREAD

**Issue by kai-wen-yang** [Hxyou/IdealGPT#2]
Hi, I want to evaluate VLM performance on VCR (with out multi-turn), how can I run it using this repo?

**Comment by Hxyou** [comment]
Setting `--max_n_rounds=1 ` when launching `blip_gpt_main.py` can switch to single-turn mode.

**Comment by kai-wen-yang** [comment]
Setting --max_n_rounds=1 still uses GPT to generate sub-questions for reasoning for one time. But I want to test only using VLM without GPT assistance.

**Comment by Hxyou** [comment]
Hi Kai-Wen, sorry for the late reply.
We attach LLava's VCR inference code in baseline/llava_model_vcr.py.
Please put this under llava's llava/eval/ and run it.
It's noted that this code is based on a older version of LLaVA (probably LLaVA-v0, I couldn't remember the specific commit number, but a very initial version when LLaVA is just released.)
